### ISSUE TITLE
Could you give me the namespace `embulk-input-google_spreadsheets`?

### ISSUE THREAD

**Issue by civitaspo** [kataring/embulk-input-google_spreadsheets#1]
Hi @kataring, I'm sorry but, could you give me the namespace `embulk-input-google_spreadsheets`?

I recreated `embulk-input-google_spreadsheets` (The old name is `embulk-input-googlespreadsheet`, see this change https://github.com/medjed/embulk-input-google_spreadsheets/pull/5). But, the gem namespace is already used and reserved by you, so I cannot use this for 98 more days (https://rubygems.org/gems/embulk-input-google_spreadsheets) .

This name is important for Embulk because `Google Spreadsheets` is the official and correct name (not googlespreadsheet), and `embulk-output-google_spreadsheets` is already released, so I wanna follow this name.

Please give me the namespace `embulk-input-google_spreadsheets`? If you can, execute this `gem owner embulk-input-google_spreadsheets --add civitaspo@gmail.com` or remove from rubygems completely.

**Comment by kataring** [comment]
done.

```
$ gem owner embulk-input-google_spreadsheets --add civitaspo@gmail.com
Owner added successfully.
Owners for gem: embulk-input-google_spreadsheets
- civitaspo@gmail.com
- kataring@gmail.com
```

**Comment by civitaspo** [comment]
Thanx a lot. After releasing new gem, I will revoke you if I can.

**Comment by kataring** [comment]
@civitaspo 

> https://github.com/kataring/embulk-input-google_spreadsheets/issues/1#issuecomment-290026044

why?  I am the owner, too.

**Comment by civitaspo** [comment]
Oh, didn't you revoke yourself? When I saw the ownership of the gem, the ownership already is abandoned. Could you check the ownership again?

Anyway, I thought "you give me the namespace" means "you abandon ownership of this namespace", didn't you? In my thoughts, you should abandon the ownership of new gem because you do not do the maintenance.
